# Generated by Django 3.1.1 on 2020-10-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20201016_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('start_grade', models.PositiveSmallIntegerField(verbose_name='Начальный класс')),
                ('end_grade', models.PositiveSmallIntegerField(verbose_name='Конечный класс')),
                ('methodist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.managers', verbose_name='Методист')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers', verbose_name='Руководитель')),
            ],
        ),
    ]
