# Generated by Django 3.1.1 on 2020-10-16 20:39

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201016_2339'),
        ('journal', '0002_auto_20201016_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciples',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Неудовлетворительно'), (1, 'Плохо')], verbose_name='Значение')),
                ('weight', models.SmallIntegerField(choices=[(4, 'Контрольная работа'), (3, 'Тест/Проверочная работа'), (2, 'Работа на уроке'), (1, 'Домашняя работа')], default=2, verbose_name='Вес')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
                ('rating_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers', verbose_name='Постановитель')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.apprentices', verbose_name='Получатель')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст домашнего задания')),
                ('file', models.FilePathField(match='.*\\.zip$|.*\\.pdf$|.*\\.png$|.*\\.jpeg$', null=True, path=journal.models.homework_path, verbose_name='Файл домашнего задания')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательность выполнения')),
                ('deadline_time', models.DateTimeField(verbose_name='Срок сдачи')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers', verbose_name='Автор')),
            ],
        ),
    ]
