# Generated by Django 3.1.1 on 2020-10-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201018_1117'),
        ('journal', '0005_auto_20201017_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый'), (6, 'Шестой'), (7, 'Седьмой'), (8, 'Восьмой'), (9, 'Девятый'), (10, 'Десятый')], null=True, verbose_name='Порядковый номер')),
                ('date', models.DateTimeField(verbose_name='Дата урока')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('homework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.homework', verbose_name='Домашнее задание')),
                ('study_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studygroups', verbose_name='Класс')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.disciples', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers', verbose_name='Преподаватель')),
            ],
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journal.lessons', verbose_name='Урок сдачи'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='placement_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journal.lessons', verbose_name='Урок установки'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.lessons', verbose_name='Урок'),
        ),
    ]
