# Generated by Django 3.1.1 on 2020-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20201028_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateField(verbose_name='Дата урока'),
        ),
    ]
