# Generated by Django 3.1.1 on 2020-11-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_lessons_auditory'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciples',
            name='color',
            field=models.CharField(default='Whitesmoke', max_length=20, verbose_name='Цвет предмета'),
        ),
    ]
