# Generated by Django 3.1.1 on 2020-11-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_disciples_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciples',
            name='color',
        ),
        migrations.AddField(
            model_name='disciples',
            name='scheme',
            field=models.CharField(default='Whitesmoke', max_length=20, verbose_name='Цветовая схема'),
        ),
    ]
