# Generated by Django 3.1.1 on 2020-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20201106_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.SmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Неудовлетворительно'), (1, 'Плохо'), (0, 'Отсутсвует')], verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='weight',
            field=models.SmallIntegerField(choices=[(4, 'Контрольная работа'), (3, 'Тест/Проверочная работа'), (2, 'Работа на уроке'), (1, 'Домашняя работа')], default=1, null=True, verbose_name='Вес'),
        ),
    ]
