# Generated by Django 3.1.1 on 2020-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_specialization_main_disciple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='rating_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата установки'),
        ),
    ]
