# Generated by Django 3.1.1 on 2020-12-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20201121_1939'),
        ('journal', '0016_auto_20201124_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworks',
            name='target_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studygroups', verbose_name='Учебная группа'),
        ),
    ]
