# Generated by Django 3.1.1 on 2020-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.TextField(max_length=20)),
                ('civ_id', models.CharField(max_length=30)),
            ],
        ),
    ]
