# Generated by Django 3.1.1 on 2020-10-16 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201016_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprentices',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='apprentices',
            name='email',
            field=models.TextField(max_length=30, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='civ_id',
            field=models.CharField(max_length=30, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='phone',
            field=models.TextField(max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.TextField(max_length=20, verbose_name='Телефон')),
                ('email', models.TextField(max_length=30, verbose_name='Электронная почта')),
                ('civ_id', models.CharField(max_length=30, verbose_name='Документ')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('symbol', models.CharField(max_length=1, verbose_name='Буква')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers', verbose_name='Куратор')),
            ],
        ),
    ]
