# Generated by Django 3.1.1 on 2020-10-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201016_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyGroup',
            new_name='StudyGroups',
        ),
    ]
