# Generated by Django 3.1.1 on 2020-10-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201016_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentices',
            name='email',
            field=models.TextField(max_length=30, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='apprentices',
            name='phone',
            field=models.TextField(max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.TextField(max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.TextField(max_length=20, verbose_name='Телефон'),
        ),
    ]
