# Generated by Django 3.1.1 on 2020-10-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20201016_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentices',
            name='study_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studygroups', verbose_name='Учебная группа'),
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('Fe', 'Female'), ('Etc', 'Other')], default='Etc', max_length=5)),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.TextField(max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.TextField(max_length=30, verbose_name='Электронная почта')),
                ('civ_id', models.CharField(max_length=30, verbose_name='Документ')),
                ('position', models.CharField(choices=[('PR', 'Principal'), ('DEW', 'Deputy of Educational Work'), ('DS', 'Deputy of Security'), ('DEA', 'Deputy of Administration and Economics'), ('SM', 'Subject Methodist'), ('GM', 'General Methodist'), ('ADM', 'Accounting Department Member'), ('ADH', 'Head of Accounting Department'), ('EDM', 'Education Department Member'), ('EDH', 'Head of Education Department'), ('HPAC', 'Head of Parental Advice Council'), ('GBM', 'Governing Council Member'), ('GBH', 'Head of Governing Council'), ('LUA', 'Labor Union Agent'), ('THW', 'Temporary Hired Worker')], default='THW', max_length=30)),
                ('registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
        ),
    ]
