# Generated by Django 3.1.1 on 2020-10-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20201016_2241'),
        ('accounts', '0008_auto_20201016_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='disciple',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.disciples', verbose_name='Специализация'),
        ),
    ]
