# Generated by Django 3.1.1 on 2020-10-16 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_teachers_disciple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentices',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Аккаунт'),
        ),
    ]
