# Generated by Django 3.1.1 on 2020-10-16 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20201016_2339'),
        ('accounts', '0013_auto_20201016_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('requirements', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studygroups',
            name='specialisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.disciples', verbose_name='Специализация'),
        ),
    ]
