# Generated by Django 3.1.1 on 2020-10-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201017_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprentices',
            name='creative_groups',
            field=models.ManyToManyField(to='accounts.CreativeGroups'),
        ),
    ]
