# Generated by Django 3.1.1 on 2020-10-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20201017_1315'),
        ('accounts', '0015_apprentices_creative_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroups',
            name='specialisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.specialization', verbose_name='Специализация'),
        ),
    ]
