# Generated by Django 3.1.1 on 2020-10-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201017_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprentices',
            name='profile_picture',
            field=models.FilePathField(match='.*\\.png$|.*\\.jpeg$', null=True, verbose_name='Картинка профиля'),
        ),
    ]
