# Generated by Django 3.1.1 on 2020-11-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201018_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentices',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_images', verbose_name='Картинка профиля'),
        ),
    ]
