# Generated by Django 3.1.1 on 2020-11-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201120_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroups',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers', verbose_name='Куратор'),
        ),
    ]
