# Generated by Django 3.1.1 on 2020-11-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201120_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroups',
            name='headman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.apprentices', verbose_name='Староста'),
        ),
        migrations.AddField(
            model_name='studygroups',
            name='methodist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.managers', verbose_name='Методист'),
        ),
    ]
