# Generated by Django 3.1.1 on 2020-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201121_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_images/', verbose_name='Картинка профиля'),
        ),
        migrations.AddField(
            model_name='parents',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_images/', verbose_name='Картинка профиля'),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_images/', verbose_name='Картинка профиля'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_images/', verbose_name='Картинка профиля'),
        ),
    ]
