# Generated by Django 3.1.1 on 2020-12-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20201121_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managers',
            old_name='registered',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='registered',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='registered',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='registered',
        ),
    ]
