# Generated by Django 3.1.1 on 2021-05-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20201221_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentices',
            name='gender',
            field=models.CharField(choices=[('M', 'Муж'), ('F', 'Жен'), ('Etc', '???')], default='Etc', max_length=5),
        ),
        migrations.AlterField(
            model_name='managers',
            name='gender',
            field=models.CharField(choices=[('M', 'Муж'), ('F', 'Жен'), ('Etc', '???')], default='Etc', max_length=5),
        ),
        migrations.AlterField(
            model_name='managers',
            name='position',
            field=models.CharField(choices=[('PR', 'Директор'), ('DEW', 'Заместитель по Воспитательной Работе'), ('DS', 'Заместитель по Безопасности'), ('DEA', 'Заместитель по Административно-хозяйственной Части'), ('SM', 'Предметный Методист'), ('GM', 'Методист Общего Образовательного Процесса'), ('ADM', 'Работник Бухгалтерии'), ('ADH', 'Глава Бухгалтерии'), ('EDM', 'Член Педагогического Совета'), ('EDH', 'Глава Педагогического Совета'), ('HPAC', 'Глава Родительского Комитета'), ('GBM', 'Глава Управляющего Совета'), ('GBH', 'Глава Управляющего Совета'), ('LUA', 'Агент Профсоюза'), ('CL', 'Главный Библиотекарь'), ('THW', 'Наемный Сотрудник')], default='THW', max_length=30),
        ),
        migrations.AlterField(
            model_name='parents',
            name='gender',
            field=models.CharField(choices=[('M', 'Муж'), ('F', 'Жен'), ('Etc', '???')], default='Etc', max_length=5),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Муж'), ('F', 'Жен'), ('Etc', '???')], default='Etc', max_length=5),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.CharField(choices=[('M', 'Муж'), ('F', 'Жен'), ('Etc', '???')], default='Etc', max_length=5),
        ),
    ]
