# Generated by Django 3.1.1 on 2020-10-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_auto_20201016_2339'),
        ('journal', '0003_auto_20201016_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый'), (6, 'Шестой'), (7, 'Седьмой'), (8, 'Восьмой'), (9, 'Девятый'), (10, 'Десятый')], null=True, verbose_name='Порядковый номер')),
                ('date', models.DateTimeField(verbose_name='Дата урока')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('homework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.homework', verbose_name='Домашнее задание')),
                ('study_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studygroups', verbose_name='Класс')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.disciples', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teachers', verbose_name='Преподаватель')),
            ],
        ),
    ]
