# Generated by Django 3.1.1 on 2020-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20201028_1616'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
